version: '3.8'

services:
  postgres:
    container_name: postgres_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Admin3030
      POSTGRES_DB: prisma
    volumes:
      - /var/lib/data/postgres
    ports:
      - '5432:5432'

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL:
      PGADMIN_DEFAULT_PASSWORD: Admin3030
      PGADMIN_LISTEN_PORT: 80
    volumes:
      - /var/lib/pgadmin

    ports:
      - 8080:80
